gantt
    title Planificación del Proyecto
    dateFormat  YYYY-MM-DD
    axisFormat  %b

    section Fase 1
    Fundamentos         :f1, 2026-01-01, 45d

    section Fase 2
    Inventario          :f2, 2026-02-01, 55d

    section Fase 3
    Base de datos       :f3, 2026-03-01, 55d

    section Fase 4
    Menú/Guardado       :f4, 2026-04-01, 55d

    section Fase 5
    Granja              :f5, 2026-05-01, 20d

    section Transversal
    Documentación/Memoria :doc, 2026-01-01, 151d